### PR TITLE
Mg create reservations

### PR DESCRIPTION
**Pull request by maggieisgreene**
- Added event listener to `Add Reservation`
- Modal pops up with input fields -- once filled out, it adds the reservation the database and calls `printReservations` again to print the reservations with the new reservation included
- Once info is enter, the input fields reset and the modal closes

-- When pull downing for review run the following in command line
`npm install moment --save`
-- NOTE: There are comments in the code -- just within the createReservations, I need to ask Zoe about how to format dates for ordering later on and don't want to forget

### CODE REVIEW

**Comment by gseals** [comment]
it looks good and it works 👍 

are we housing our modals in the same place? are modals called by ids or is there a chance they'll interact with each other? stretch: the system should kick back a reservation if it is attempted on a table too small for party size.

**Comment by gseals** [comment]
are we housing our modals in the same place? are modals called by ids or is there a chance they'll interact with each other? considerations: the system should kick back a reservation if it is attempted on a table too small for party size. also, the system should prompt if a table is taken on the day and time it is reserved

**Comment by gseals** [comment]
it looks great! :+1: 

down the line, we should consider allowing the system to prompt when someone else has the table for the exact time and when a user is attempting to reserve a table too small for a party too large

**Comment by maggieisgreene** [comment]
@gseals totally agree! I'll see what I can do! I may put that on the filter branch.

**Pull request merged**
